#!/bin/bash
if [ -n "$1" ]; then

	#by using a template and sed, we can create new zones easily
	#first we add the new zone in the placeholder and then place that text into our master zone file
	sed "s/change/$1/g" /etc/bind/zones/.template.db.zone > /etc/bind/zones/db."$1".ruben-vandekerckhove.sb.uclllabs.be


	#now we add the new zone to the local
	sed "s/change/$1/g" /etc/bind/.addzone.named.conf.local >> /etc/bind/named.conf.local

	#we can now add a record to our master zone file	
	printf "\n$1	IN	NS	ns.ruben-vandekerckhove.sb.uclllabs.be." >> /etc/bind/zones/db.ruben-vandekerckhove.sb.uclllabs.be


	#serial + 1
	serial_nr=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/zones/db.ruben-vandekerckhove.sb.uclllabs.be)
	serial_comp=$(grep -Po '\d+\s+; Serial' /etc/bind/zones/db.ruben-vandekerckhove.sb.uclllabs.be)
	serial_ln=$(grep -Po '\s+; Serial' /etc/bind/zones/db.ruben-vandekerckhove.sb.uclllabs.be)
	serial_updated=$(("$serial_nr" + 1))

	sed -i "s/$serial_comp/$serial_updated$serial_ln/g" /etc/bind/zones/db.ruben-vandekerckhove.sb.uclllabs.be

	chmod 644 /etc/bind/zones/db."$1".ruben-vandekerckhove.sb.uclllabs.be

	rndc reload
	systemctl restart bind9

else

	printf "The argument is invalid."

fi
