#!/bin/sh

updaten(){
# fix debian /usr/local sgid stuff
chmod g-s /usr/local
chgrp root /usr/local
chmod 755 /usr/local

# On a fresh install, add the necessary user and group
adduser --quiet --system --no-create-home --home /etc/freeradius --group --disabled-password freerad
# Put user freerad in group shadow, so the daemon can auth locally
adduser --quiet freerad shadow
adduser --quiet freerad ssl-cert

# clone the freeradius git repository
cd /usr/local/src
git clone https://github.com/FreeRADIUS/freeradius-server
cd freeradius-server
git checkout v3.0.x
git pull origin
git log -n 1 --pretty=format:%h

# make sure you get a clean build and don't have left-over by-products from previous run:
make clean

# output git log with :
# -n limit 1 line
# Pretty-print commit content in hash format (%h)
hash=`git log -n 1 --pretty=format:%h`
./configure \
        --prefix="/usr/local/freeradius-$hash" \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --disable-developer
#       --with-openssl \                                # default now
rm -rf /usr/local/freeradius-$hash/
unlink /usr/local/freeradius/
# build executable program and lib from source code:
make
# copy built program, its libraries and documentation to current locations:
make install

mkdir /usr/local/etc
#mv /usr/local/freeradius-$hash/etc/raddb /usr/local/etc
rm -rf /usr/local/freeradius-$hash/etc/raddb
ln -s /usr/local/etc/raddb /usr/local/freeradius-$hash/etc/raddb
#ln -s /usr/local/freeradius-$hash /usr/local/freeradius

#fix permissions
chgrp -R freerad /usr/local/etc
find /usr/local/etc -type f -print0 | xargs -0 chmod 640
find /usr/local/etc -type d -print0 | xargs -0 chmod 750
chmod g+s /usr/local/etc/raddb/sites-available
chmod g+s /usr/local/etc/raddb/sites-enabled
chmod g+s /usr/local/etc/raddb/certs
}

#outp=$(/etc/init.d/freeradius configtest | tail -c 4)
#strn=" OK "

service freeradius configtest && updaten || echo "config errors"

#if [ service freeradius configtest ]
#then
        #updaten
#	echo "config ok"
#else
#        echo "Config has errors"
#fi
